import React from 'react';

import axios from 'axios';

export default class PersonList extends React.Component {
  state = {
    persons: []
  }

  componentDidMount() {
    axios.get(`https://api.darksky.net/forecast/14fce45d400e69e72b9aef92bad8550b/37.8267,-122.4233`)
      .then(res => {
        // const persons = res.data;
        // this.setState({ persons });
        console.log(res);
      })
  }

  render() {
    let data={
        "latitude": 37.8267,
        "longitude": -122.4233,
        "timezone": "America/Los_Angeles",
        "currently": {
            "time": 1569661809,
            "summary": "Mostly Cloudy",
            "icon": "partly-cloudy-night",
            "nearestStormDistance": 12,
            "nearestStormBearing": 337,
            "precipIntensity": 0,
            "precipProbability": 0,
            "temperature": 55.99,
            "apparentTemperature": 55.99,
            "dewPoint": 48,
            "humidity": 0.74,
            "pressure": 1008.14,
            "windSpeed": 8.69,
            "windGust": 13.27,
            "windBearing": 262,
            "cloudCover": 0.84,
            "uvIndex": 0,
            "visibility": 10,
            "ozone": 303
        },
        "minutely": {
            "summary": "Mostly cloudy for the hour.",
            "icon": "partly-cloudy-night",
            "data": [
                {
                    "time": 1569661800,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569661860,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569661920,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569661980,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569662040,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569662100,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569662160,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569662220,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569662280,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569662340,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569662400,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569662460,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569662520,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569662580,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569662640,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569662700,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569662760,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569662820,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569662880,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569662940,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569663000,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569663060,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569663120,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569663180,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569663240,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569663300,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569663360,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569663420,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569663480,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569663540,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569663600,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569663660,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569663720,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569663780,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569663840,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569663900,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569663960,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569664020,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569664080,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569664140,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569664200,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569664260,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569664320,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569664380,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569664440,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569664500,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569664560,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569664620,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569664680,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569664740,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569664800,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569664860,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569664920,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569664980,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569665040,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569665100,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569665160,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569665220,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569665280,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569665340,
                    "precipIntensity": 0,
                    "precipProbability": 0
                },
                {
                    "time": 1569665400,
                    "precipIntensity": 0,
                    "precipProbability": 0
                }
            ]
        },
        "hourly": {
            "summary": "Partly cloudy throughout the day.",
            "icon": "clear-day",
            "data": [
                {
                    "time": 1569661200,
                    "summary": "Mostly Cloudy",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 56.11,
                    "apparentTemperature": 56.11,
                    "dewPoint": 48.13,
                    "humidity": 0.75,
                    "pressure": 1008.2,
                    "windSpeed": 8.69,
                    "windGust": 13.03,
                    "windBearing": 263,
                    "cloudCover": 0.86,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 302.4
                },
                {
                    "time": 1569664800,
                    "summary": "Mostly Cloudy",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 55.44,
                    "apparentTemperature": 55.44,
                    "dewPoint": 47.38,
                    "humidity": 0.74,
                    "pressure": 1007.85,
                    "windSpeed": 8.71,
                    "windGust": 14.42,
                    "windBearing": 255,
                    "cloudCover": 0.74,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 306.2
                },
                {
                    "time": 1569668400,
                    "summary": "Partly Cloudy",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0.0015,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 55.62,
                    "apparentTemperature": 55.62,
                    "dewPoint": 47.04,
                    "humidity": 0.73,
                    "pressure": 1007.4,
                    "windSpeed": 10.84,
                    "windGust": 18.93,
                    "windBearing": 294,
                    "cloudCover": 0.33,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 310.3
                },
                {
                    "time": 1569672000,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 55.54,
                    "apparentTemperature": 55.54,
                    "dewPoint": 46.88,
                    "humidity": 0.73,
                    "pressure": 1006.72,
                    "windSpeed": 11.86,
                    "windGust": 20.6,
                    "windBearing": 295,
                    "cloudCover": 0.07,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 313.1
                },
                {
                    "time": 1569675600,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 54.87,
                    "apparentTemperature": 54.87,
                    "dewPoint": 46.85,
                    "humidity": 0.74,
                    "pressure": 1006.83,
                    "windSpeed": 11.63,
                    "windGust": 19.87,
                    "windBearing": 300,
                    "cloudCover": 0.04,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 313.7
                },
                {
                    "time": 1569679200,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 54.2,
                    "apparentTemperature": 54.2,
                    "dewPoint": 46.86,
                    "humidity": 0.76,
                    "pressure": 1007.29,
                    "windSpeed": 11.47,
                    "windGust": 19.48,
                    "windBearing": 295,
                    "cloudCover": 0.02,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 313.1
                },
                {
                    "time": 1569682800,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 55.03,
                    "apparentTemperature": 55.03,
                    "dewPoint": 47.22,
                    "humidity": 0.75,
                    "pressure": 1007.83,
                    "windSpeed": 12.02,
                    "windGust": 20.85,
                    "windBearing": 298,
                    "cloudCover": 0,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 312.7
                },
                {
                    "time": 1569686400,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0.0015,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                    "temperature": 57.31,
                    "apparentTemperature": 57.31,
                    "dewPoint": 47.25,
                    "humidity": 0.69,
                    "pressure": 1008.86,
                    "windSpeed": 13.85,
                    "windGust": 24.33,
                    "windBearing": 287,
                    "cloudCover": 0,
                    "uvIndex": 1,
                    "visibility": 10,
                    "ozone": 313.1
                },
                {
                    "time": 1569690000,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0.0011,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 59.5,
                    "apparentTemperature": 59.5,
                    "dewPoint": 47.47,
                    "humidity": 0.64,
                    "pressure": 1009.31,
                    "windSpeed": 14.69,
                    "windGust": 24.41,
                    "windBearing": 316,
                    "cloudCover": 0,
                    "uvIndex": 3,
                    "visibility": 10,
                    "ozone": 313.8
                },
                {
                    "time": 1569693600,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0.0016,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                    "temperature": 60.72,
                    "apparentTemperature": 60.72,
                    "dewPoint": 47.08,
                    "humidity": 0.61,
                    "pressure": 1009.46,
                    "windSpeed": 15.22,
                    "windGust": 24.54,
                    "windBearing": 300,
                    "cloudCover": 0,
                    "uvIndex": 4,
                    "visibility": 10,
                    "ozone": 315
                },
                {
                    "time": 1569697200,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 61.86,
                    "apparentTemperature": 61.86,
                    "dewPoint": 46.89,
                    "humidity": 0.58,
                    "pressure": 1008.91,
                    "windSpeed": 16.23,
                    "windGust": 25.03,
                    "windBearing": 296,
                    "cloudCover": 0,
                    "uvIndex": 5,
                    "visibility": 10,
                    "ozone": 317.1
                },
                {
                    "time": 1569700800,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 62.63,
                    "apparentTemperature": 62.63,
                    "dewPoint": 47.15,
                    "humidity": 0.57,
                    "pressure": 1008.46,
                    "windSpeed": 17.44,
                    "windGust": 25.84,
                    "windBearing": 295,
                    "cloudCover": 0,
                    "uvIndex": 6,
                    "visibility": 10,
                    "ozone": 319.6
                },
                {
                    "time": 1569704400,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 62.92,
                    "apparentTemperature": 62.92,
                    "dewPoint": 47.59,
                    "humidity": 0.57,
                    "pressure": 1007.78,
                    "windSpeed": 18.35,
                    "windGust": 26.65,
                    "windBearing": 295,
                    "cloudCover": 0,
                    "uvIndex": 5,
                    "visibility": 10,
                    "ozone": 322.1
                },
                {
                    "time": 1569708000,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 62.89,
                    "apparentTemperature": 62.89,
                    "dewPoint": 47.86,
                    "humidity": 0.58,
                    "pressure": 1007.62,
                    "windSpeed": 19.25,
                    "windGust": 28.39,
                    "windBearing": 295,
                    "cloudCover": 0,
                    "uvIndex": 4,
                    "visibility": 10,
                    "ozone": 324.2
                },
                {
                    "time": 1569711600,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 63.78,
                    "apparentTemperature": 63.78,
                    "dewPoint": 48.1,
                    "humidity": 0.57,
                    "pressure": 1007.33,
                    "windSpeed": 19.23,
                    "windGust": 26.27,
                    "windBearing": 291,
                    "cloudCover": 0,
                    "uvIndex": 2,
                    "visibility": 10,
                    "ozone": 326.2
                },
                {
                    "time": 1569715200,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 62.46,
                    "apparentTemperature": 62.46,
                    "dewPoint": 47.91,
                    "humidity": 0.59,
                    "pressure": 1007.3,
                    "windSpeed": 19.93,
                    "windGust": 28.55,
                    "windBearing": 291,
                    "cloudCover": 0,
                    "uvIndex": 1,
                    "visibility": 10,
                    "ozone": 327.8
                },
                {
                    "time": 1569718800,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 61.08,
                    "apparentTemperature": 61.08,
                    "dewPoint": 47.35,
                    "humidity": 0.61,
                    "pressure": 1007.28,
                    "windSpeed": 19.62,
                    "windGust": 29.71,
                    "windBearing": 291,
                    "cloudCover": 0,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 329.1
                },
                {
                    "time": 1569722400,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 59.56,
                    "apparentTemperature": 59.56,
                    "dewPoint": 47.02,
                    "humidity": 0.63,
                    "pressure": 1007.33,
                    "windSpeed": 18.66,
                    "windGust": 30.26,
                    "windBearing": 296,
                    "cloudCover": 0,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 330
                },
                {
                    "time": 1569726000,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 58.56,
                    "apparentTemperature": 58.56,
                    "dewPoint": 47.21,
                    "humidity": 0.66,
                    "pressure": 1007.59,
                    "windSpeed": 17.56,
                    "windGust": 30.25,
                    "windBearing": 296,
                    "cloudCover": 0,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 330
                },
                {
                    "time": 1569729600,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 58.15,
                    "apparentTemperature": 58.15,
                    "dewPoint": 46.94,
                    "humidity": 0.66,
                    "pressure": 1008.66,
                    "windSpeed": 16.51,
                    "windGust": 29.69,
                    "windBearing": 300,
                    "cloudCover": 0,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 328.5
                },
                {
                    "time": 1569733200,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 57.88,
                    "apparentTemperature": 57.88,
                    "dewPoint": 46.38,
                    "humidity": 0.65,
                    "pressure": 1009.52,
                    "windSpeed": 15.36,
                    "windGust": 28.55,
                    "windBearing": 303,
                    "cloudCover": 0,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 326
                },
                {
                    "time": 1569736800,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0.0002,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 57.59,
                    "apparentTemperature": 57.59,
                    "dewPoint": 45.83,
                    "humidity": 0.65,
                    "pressure": 1010.19,
                    "windSpeed": 14.14,
                    "windGust": 26.83,
                    "windBearing": 306,
                    "cloudCover": 0,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 324.8
                },
                {
                    "time": 1569740400,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0.0002,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 57.23,
                    "apparentTemperature": 57.23,
                    "dewPoint": 45.31,
                    "humidity": 0.64,
                    "pressure": 1010.67,
                    "windSpeed": 12.73,
                    "windGust": 24.14,
                    "windBearing": 308,
                    "cloudCover": 0,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 326
                },
                {
                    "time": 1569744000,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 57.06,
                    "apparentTemperature": 57.06,
                    "dewPoint": 44.68,
                    "humidity": 0.63,
                    "pressure": 1010.84,
                    "windSpeed": 11.24,
                    "windGust": 20.88,
                    "windBearing": 308,
                    "cloudCover": 0,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 328.3
                },
                {
                    "time": 1569747600,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 56.88,
                    "apparentTemperature": 56.88,
                    "dewPoint": 44.24,
                    "humidity": 0.63,
                    "pressure": 1011.12,
                    "windSpeed": 10.04,
                    "windGust": 18.06,
                    "windBearing": 309,
                    "cloudCover": 0,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 330.2
                },
                {
                    "time": 1569751200,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 56.32,
                    "apparentTemperature": 56.32,
                    "dewPoint": 44.03,
                    "humidity": 0.63,
                    "pressure": 1010.69,
                    "windSpeed": 9.34,
                    "windGust": 15.95,
                    "windBearing": 307,
                    "cloudCover": 0,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 331.3
                },
                {
                    "time": 1569754800,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 55.38,
                    "apparentTemperature": 55.38,
                    "dewPoint": 44.01,
                    "humidity": 0.66,
                    "pressure": 1010.42,
                    "windSpeed": 8.93,
                    "windGust": 14.3,
                    "windBearing": 302,
                    "cloudCover": 0,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 332
                },
                {
                    "time": 1569758400,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 54.73,
                    "apparentTemperature": 54.73,
                    "dewPoint": 44.29,
                    "humidity": 0.68,
                    "pressure": 1010.39,
                    "windSpeed": 8.64,
                    "windGust": 13.17,
                    "windBearing": 301,
                    "cloudCover": 0,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 333.1
                },
                {
                    "time": 1569762000,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0.0004,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 54.22,
                    "apparentTemperature": 54.22,
                    "dewPoint": 44.91,
                    "humidity": 0.71,
                    "pressure": 1011.21,
                    "windSpeed": 8.4,
                    "windGust": 12.77,
                    "windBearing": 304,
                    "cloudCover": 0.02,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 335.4
                },
                {
                    "time": 1569765600,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0.0024,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                    "temperature": 53.9,
                    "apparentTemperature": 53.9,
                    "dewPoint": 45.95,
                    "humidity": 0.74,
                    "pressure": 1012.04,
                    "windSpeed": 8.26,
                    "windGust": 12.9,
                    "windBearing": 285,
                    "cloudCover": 0.05,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 337.9
                },
                {
                    "time": 1569769200,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0.0039,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                    "temperature": 54.37,
                    "apparentTemperature": 54.37,
                    "dewPoint": 47,
                    "humidity": 0.76,
                    "pressure": 1012.77,
                    "windSpeed": 8.32,
                    "windGust": 13.16,
                    "windBearing": 293,
                    "cloudCover": 0.07,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 339
                },
                {
                    "time": 1569772800,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0.0025,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                    "temperature": 56.15,
                    "apparentTemperature": 56.15,
                    "dewPoint": 47.71,
                    "humidity": 0.73,
                    "pressure": 1013,
                    "windSpeed": 8.57,
                    "windGust": 13.42,
                    "windBearing": 303,
                    "cloudCover": 0.04,
                    "uvIndex": 1,
                    "visibility": 10,
                    "ozone": 337.5
                },
                {
                    "time": 1569776400,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0.0014,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                    "temperature": 58.18,
                    "apparentTemperature": 58.18,
                    "dewPoint": 48.33,
                    "humidity": 0.7,
                    "pressure": 1013.28,
                    "windSpeed": 9.06,
                    "windGust": 13.83,
                    "windBearing": 269,
                    "cloudCover": 0.01,
                    "uvIndex": 2,
                    "visibility": 10,
                    "ozone": 334.5
                },
                {
                    "time": 1569780000,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0.0021,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                    "temperature": 58.96,
                    "apparentTemperature": 58.96,
                    "dewPoint": 48.48,
                    "humidity": 0.68,
                    "pressure": 1013.63,
                    "windSpeed": 9.88,
                    "windGust": 14.49,
                    "windBearing": 277,
                    "cloudCover": 0,
                    "uvIndex": 4,
                    "visibility": 10,
                    "ozone": 332.1
                },
                {
                    "time": 1569783600,
                    "summary": "Partly Cloudy",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0032,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                    "temperature": 59.68,
                    "apparentTemperature": 59.68,
                    "dewPoint": 48.85,
                    "humidity": 0.67,
                    "pressure": 1013.62,
                    "windSpeed": 11.39,
                    "windGust": 15.61,
                    "windBearing": 292,
                    "cloudCover": 0.16,
                    "uvIndex": 5,
                    "visibility": 10,
                    "ozone": 331.1
                },
                {
                    "time": 1569787200,
                    "summary": "Partly Cloudy",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0039,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                    "temperature": 60.11,
                    "apparentTemperature": 60.11,
                    "dewPoint": 49.35,
                    "humidity": 0.68,
                    "pressure": 1013.6,
                    "windSpeed": 13.19,
                    "windGust": 16.97,
                    "windBearing": 246,
                    "cloudCover": 0.39,
                    "uvIndex": 5,
                    "visibility": 10,
                    "ozone": 330.8
                },
                {
                    "time": 1569790800,
                    "summary": "Mostly Cloudy",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0038,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                    "temperature": 60.41,
                    "apparentTemperature": 60.41,
                    "dewPoint": 49.76,
                    "humidity": 0.68,
                    "pressure": 1013.33,
                    "windSpeed": 14.41,
                    "windGust": 18.03,
                    "windBearing": 261,
                    "cloudCover": 0.5,
                    "uvIndex": 4,
                    "visibility": 10,
                    "ozone": 331.2
                },
                {
                    "time": 1569794400,
                    "summary": "Partly Cloudy",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0024,
                    "precipProbability": 0.06,
                    "precipType": "rain",
                    "temperature": 60.54,
                    "apparentTemperature": 60.54,
                    "dewPoint": 50.07,
                    "humidity": 0.68,
                    "pressure": 1012.8,
                    "windSpeed": 14.71,
                    "windGust": 18.65,
                    "windBearing": 263,
                    "cloudCover": 0.39,
                    "uvIndex": 3,
                    "visibility": 10,
                    "ozone": 333
                },
                {
                    "time": 1569798000,
                    "summary": "Partly Cloudy",
                    "icon": "partly-cloudy-day",
                    "precipIntensity": 0.0023,
                    "precipProbability": 0.07,
                    "precipType": "rain",
                    "temperature": 60.15,
                    "apparentTemperature": 60.15,
                    "dewPoint": 50.2,
                    "humidity": 0.7,
                    "pressure": 1012.34,
                    "windSpeed": 14.44,
                    "windGust": 19.01,
                    "windBearing": 262,
                    "cloudCover": 0.17,
                    "uvIndex": 2,
                    "visibility": 10,
                    "ozone": 335.5
                },
                {
                    "time": 1569801600,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0.003,
                    "precipProbability": 0.08,
                    "precipType": "rain",
                    "temperature": 59.72,
                    "apparentTemperature": 59.72,
                    "dewPoint": 49.89,
                    "humidity": 0.7,
                    "pressure": 1012.09,
                    "windSpeed": 13.88,
                    "windGust": 19.04,
                    "windBearing": 266,
                    "cloudCover": 0,
                    "uvIndex": 1,
                    "visibility": 10,
                    "ozone": 337.3
                },
                {
                    "time": 1569805200,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0.0021,
                    "precipProbability": 0.05,
                    "precipType": "rain",
                    "temperature": 59.08,
                    "apparentTemperature": 59.08,
                    "dewPoint": 49.56,
                    "humidity": 0.71,
                    "pressure": 1012.22,
                    "windSpeed": 13.03,
                    "windGust": 18.66,
                    "windBearing": 234,
                    "cloudCover": 0.01,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 337.5
                },
                {
                    "time": 1569808800,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0.0007,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                    "temperature": 58.18,
                    "apparentTemperature": 58.18,
                    "dewPoint": 49.26,
                    "humidity": 0.72,
                    "pressure": 1012.43,
                    "windSpeed": 11.92,
                    "windGust": 18,
                    "windBearing": 317,
                    "cloudCover": 0.02,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 337
                },
                {
                    "time": 1569812400,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0.0002,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                    "temperature": 57.33,
                    "apparentTemperature": 57.33,
                    "dewPoint": 49.67,
                    "humidity": 0.76,
                    "pressure": 1012.63,
                    "windSpeed": 10.97,
                    "windGust": 17.36,
                    "windBearing": 277,
                    "cloudCover": 0.02,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 336.9
                },
                {
                    "time": 1569816000,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 56.59,
                    "apparentTemperature": 56.59,
                    "dewPoint": 49.5,
                    "humidity": 0.77,
                    "pressure": 1012.99,
                    "windSpeed": 10.34,
                    "windGust": 16.97,
                    "windBearing": 267,
                    "cloudCover": 0.02,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 337.4
                },
                {
                    "time": 1569819600,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0.0002,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                    "temperature": 55.93,
                    "apparentTemperature": 55.93,
                    "dewPoint": 49.07,
                    "humidity": 0.78,
                    "pressure": 1013.28,
                    "windSpeed": 9.85,
                    "windGust": 16.63,
                    "windBearing": 285,
                    "cloudCover": 0.01,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 338.2
                },
                {
                    "time": 1569823200,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0.0004,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                    "temperature": 55.42,
                    "apparentTemperature": 55.42,
                    "dewPoint": 48.69,
                    "humidity": 0.78,
                    "pressure": 1013.56,
                    "windSpeed": 9.4,
                    "windGust": 16.1,
                    "windBearing": 284,
                    "cloudCover": 0.01,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 338.8
                },
                {
                    "time": 1569826800,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0.0004,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                    "temperature": 55.06,
                    "apparentTemperature": 55.06,
                    "dewPoint": 48.43,
                    "humidity": 0.78,
                    "pressure": 1013.77,
                    "windSpeed": 8.94,
                    "windGust": 15.1,
                    "windBearing": 285,
                    "cloudCover": 0.01,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 338.9
                },
                {
                    "time": 1569830400,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0.0005,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                    "temperature": 54.81,
                    "apparentTemperature": 54.81,
                    "dewPoint": 48.16,
                    "humidity": 0.78,
                    "pressure": 1014.01,
                    "windSpeed": 8.49,
                    "windGust": 13.89,
                    "windBearing": 282,
                    "cloudCover": 0,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 338.8
                },
                {
                    "time": 1569834000,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0.0004,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                    "temperature": 54.6,
                    "apparentTemperature": 54.6,
                    "dewPoint": 47.91,
                    "humidity": 0.78,
                    "pressure": 1014.02,
                    "windSpeed": 8.14,
                    "windGust": 12.97,
                    "windBearing": 283,
                    "cloudCover": 0,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 338.5
                }
            ]
        },
        "daily": {
            "summary": "No precipitation throughout the week, with high temperatures rising to 73°F on Thursday.",
            "icon": "clear-day",
            "data": [
                {
                    "time": 1569654000,
                    "summary": "Clear throughout the day.",
                    "icon": "clear-day",
                    "sunriseTime": 1569679436,
                    "sunsetTime": 1569722348,
                    "moonPhase": 0.02,
                    "precipIntensity": 0.0003,
                    "precipIntensityMax": 0.0016,
                    "precipIntensityMaxTime": 1569693600,
                    "precipProbability": 0.05,
                    "precipType": "rain",
                    "temperatureHigh": 63.78,
                    "temperatureHighTime": 1569711600,
                    "temperatureLow": 53.9,
                    "temperatureLowTime": 1569765600,
                    "apparentTemperatureHigh": 63.78,
                    "apparentTemperatureHighTime": 1569711600,
                    "apparentTemperatureLow": 53.9,
                    "apparentTemperatureLowTime": 1569765600,
                    "dewPoint": 47.28,
                    "humidity": 0.67,
                    "pressure": 1008.23,
                    "windSpeed": 14.46,
                    "windGust": 30.26,
                    "windGustTime": 1569722400,
                    "windBearing": 294,
                    "cloudCover": 0.16,
                    "uvIndex": 6,
                    "uvIndexTime": 1569700800,
                    "visibility": 10,
                    "ozone": 317.7,
                    "temperatureMin": 54.2,
                    "temperatureMinTime": 1569679200,
                    "temperatureMax": 63.78,
                    "temperatureMaxTime": 1569711600,
                    "apparentTemperatureMin": 54.2,
                    "apparentTemperatureMinTime": 1569679200,
                    "apparentTemperatureMax": 63.78,
                    "apparentTemperatureMaxTime": 1569711600
                },
                {
                    "time": 1569740400,
                    "summary": "Partly cloudy throughout the day.",
                    "icon": "partly-cloudy-day",
                    "sunriseTime": 1569765888,
                    "sunsetTime": 1569808655,
                    "moonPhase": 0.05,
                    "precipIntensity": 0.0014,
                    "precipIntensityMax": 0.0039,
                    "precipIntensityMaxTime": 1569787200,
                    "precipProbability": 0.21,
                    "precipType": "rain",
                    "temperatureHigh": 60.54,
                    "temperatureHighTime": 1569794400,
                    "temperatureLow": 52.04,
                    "temperatureLowTime": 1569852000,
                    "apparentTemperatureHigh": 60.54,
                    "apparentTemperatureHighTime": 1569794400,
                    "apparentTemperatureLow": 52.04,
                    "apparentTemperatureLowTime": 1569852000,
                    "dewPoint": 47.65,
                    "humidity": 0.7,
                    "pressure": 1012.35,
                    "windSpeed": 10.8,
                    "windGust": 24.14,
                    "windGustTime": 1569740400,
                    "windBearing": 282,
                    "cloudCover": 0.08,
                    "uvIndex": 5,
                    "uvIndexTime": 1569783600,
                    "visibility": 10,
                    "ozone": 334.4,
                    "temperatureMin": 53.9,
                    "temperatureMinTime": 1569765600,
                    "temperatureMax": 60.54,
                    "temperatureMaxTime": 1569794400,
                    "apparentTemperatureMin": 53.9,
                    "apparentTemperatureMinTime": 1569765600,
                    "apparentTemperatureMax": 60.54,
                    "apparentTemperatureMaxTime": 1569794400
                },
                {
                    "time": 1569826800,
                    "summary": "Partly cloudy throughout the day.",
                    "icon": "clear-day",
                    "sunriseTime": 1569852340,
                    "sunsetTime": 1569894962,
                    "moonPhase": 0.09,
                    "precipIntensity": 0.0002,
                    "precipIntensityMax": 0.0005,
                    "precipIntensityMaxTime": 1569830400,
                    "precipProbability": 0.11,
                    "precipType": "rain",
                    "temperatureHigh": 61.44,
                    "temperatureHighTime": 1569880800,
                    "temperatureLow": 53.36,
                    "temperatureLowTime": 1569938400,
                    "apparentTemperatureHigh": 61.44,
                    "apparentTemperatureHighTime": 1569880800,
                    "apparentTemperatureLow": 53.36,
                    "apparentTemperatureLowTime": 1569938400,
                    "dewPoint": 47.47,
                    "humidity": 0.73,
                    "pressure": 1014.97,
                    "windSpeed": 7.7,
                    "windGust": 15.1,
                    "windGustTime": 1569826800,
                    "windBearing": 287,
                    "cloudCover": 0.06,
                    "uvIndex": 5,
                    "uvIndexTime": 1569873600,
                    "visibility": 10,
                    "ozone": 336.9,
                    "temperatureMin": 52.04,
                    "temperatureMinTime": 1569852000,
                    "temperatureMax": 61.44,
                    "temperatureMaxTime": 1569880800,
                    "apparentTemperatureMin": 52.04,
                    "apparentTemperatureMinTime": 1569852000,
                    "apparentTemperatureMax": 61.44,
                    "apparentTemperatureMaxTime": 1569880800
                },
                {
                    "time": 1569913200,
                    "summary": "Clear throughout the day.",
                    "icon": "clear-day",
                    "sunriseTime": 1569938792,
                    "sunsetTime": 1569981269,
                    "moonPhase": 0.13,
                    "precipIntensity": 0.0001,
                    "precipIntensityMax": 0.0003,
                    "precipIntensityMaxTime": 1569945600,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                    "temperatureHigh": 64.58,
                    "temperatureHighTime": 1569963600,
                    "temperatureLow": 54.37,
                    "temperatureLowTime": 1570024800,
                    "apparentTemperatureHigh": 64.58,
                    "apparentTemperatureHighTime": 1569963600,
                    "apparentTemperatureLow": 54.37,
                    "apparentTemperatureLowTime": 1570024800,
                    "dewPoint": 46.42,
                    "humidity": 0.65,
                    "pressure": 1015.01,
                    "windSpeed": 6.19,
                    "windGust": 14.12,
                    "windGustTime": 1569974400,
                    "windBearing": 271,
                    "cloudCover": 0,
                    "uvIndex": 6,
                    "uvIndexTime": 1569960000,
                    "visibility": 10,
                    "ozone": 312.6,
                    "temperatureMin": 53.36,
                    "temperatureMinTime": 1569938400,
                    "temperatureMax": 64.58,
                    "temperatureMaxTime": 1569963600,
                    "apparentTemperatureMin": 53.36,
                    "apparentTemperatureMinTime": 1569938400,
                    "apparentTemperatureMax": 64.58,
                    "apparentTemperatureMaxTime": 1569963600
                },
                {
                    "time": 1569999600,
                    "summary": "Clear throughout the day.",
                    "icon": "clear-day",
                    "sunriseTime": 1570025244,
                    "sunsetTime": 1570067577,
                    "moonPhase": 0.17,
                    "precipIntensity": 0.0001,
                    "precipIntensityMax": 0.0002,
                    "precipIntensityMaxTime": 1570014000,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                    "temperatureHigh": 71.04,
                    "temperatureHighTime": 1570053600,
                    "temperatureLow": 56.01,
                    "temperatureLowTime": 1570111200,
                    "apparentTemperatureHigh": 71.04,
                    "apparentTemperatureHighTime": 1570053600,
                    "apparentTemperatureLow": 56.01,
                    "apparentTemperatureLowTime": 1570111200,
                    "dewPoint": 48.02,
                    "humidity": 0.63,
                    "pressure": 1016.55,
                    "windSpeed": 4.44,
                    "windGust": 12.02,
                    "windGustTime": 1570060800,
                    "windBearing": 277,
                    "cloudCover": 0,
                    "uvIndex": 6,
                    "uvIndexTime": 1570046400,
                    "visibility": 10,
                    "ozone": 293.2,
                    "temperatureMin": 54.37,
                    "temperatureMinTime": 1570024800,
                    "temperatureMax": 71.04,
                    "temperatureMaxTime": 1570053600,
                    "apparentTemperatureMin": 54.37,
                    "apparentTemperatureMinTime": 1570024800,
                    "apparentTemperatureMax": 71.04,
                    "apparentTemperatureMaxTime": 1570053600
                },
                {
                    "time": 1570086000,
                    "summary": "Clear throughout the day.",
                    "icon": "clear-day",
                    "sunriseTime": 1570111697,
                    "sunsetTime": 1570153885,
                    "moonPhase": 0.2,
                    "precipIntensity": 0.0001,
                    "precipIntensityMax": 0.0004,
                    "precipIntensityMaxTime": 1570129200,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperatureHigh": 72.55,
                    "temperatureHighTime": 1570136400,
                    "temperatureLow": 54.7,
                    "temperatureLowTime": 1570197600,
                    "apparentTemperatureHigh": 72.55,
                    "apparentTemperatureHighTime": 1570136400,
                    "apparentTemperatureLow": 54.7,
                    "apparentTemperatureLowTime": 1570197600,
                    "dewPoint": 50.08,
                    "humidity": 0.65,
                    "pressure": 1014.49,
                    "windSpeed": 4.58,
                    "windGust": 12.26,
                    "windGustTime": 1570147200,
                    "windBearing": 265,
                    "cloudCover": 0,
                    "uvIndex": 6,
                    "uvIndexTime": 1570132800,
                    "visibility": 10,
                    "ozone": 285.2,
                    "temperatureMin": 56.01,
                    "temperatureMinTime": 1570111200,
                    "temperatureMax": 72.55,
                    "temperatureMaxTime": 1570136400,
                    "apparentTemperatureMin": 56.01,
                    "apparentTemperatureMinTime": 1570111200,
                    "apparentTemperatureMax": 72.55,
                    "apparentTemperatureMaxTime": 1570136400
                },
                {
                    "time": 1570172400,
                    "summary": "Partly cloudy throughout the day.",
                    "icon": "clear-day",
                    "sunriseTime": 1570198150,
                    "sunsetTime": 1570240194,
                    "moonPhase": 0.23,
                    "precipIntensity": 0,
                    "precipIntensityMax": 0,
                    "precipProbability": 0,
                    "temperatureHigh": 66.56,
                    "temperatureHighTime": 1570222800,
                    "temperatureLow": 54.16,
                    "temperatureLowTime": 1570284000,
                    "apparentTemperatureHigh": 66.56,
                    "apparentTemperatureHighTime": 1570222800,
                    "apparentTemperatureLow": 54.16,
                    "apparentTemperatureLowTime": 1570284000,
                    "dewPoint": 51.41,
                    "humidity": 0.74,
                    "pressure": 1013.44,
                    "windSpeed": 6.21,
                    "windGust": 15.61,
                    "windGustTime": 1570233600,
                    "windBearing": 247,
                    "cloudCover": 0.19,
                    "uvIndex": 6,
                    "uvIndexTime": 1570219200,
                    "visibility": 10,
                    "ozone": 288.5,
                    "temperatureMin": 54.7,
                    "temperatureMinTime": 1570197600,
                    "temperatureMax": 66.56,
                    "temperatureMaxTime": 1570222800,
                    "apparentTemperatureMin": 54.7,
                    "apparentTemperatureMinTime": 1570197600,
                    "apparentTemperatureMax": 66.56,
                    "apparentTemperatureMaxTime": 1570222800
                },
                {
                    "time": 1570258800,
                    "summary": "Clear throughout the day.",
                    "icon": "clear-day",
                    "sunriseTime": 1570284604,
                    "sunsetTime": 1570326503,
                    "moonPhase": 0.27,
                    "precipIntensity": 0.0001,
                    "precipIntensityMax": 0.0003,
                    "precipIntensityMaxTime": 1570341600,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperatureHigh": 69.42,
                    "temperatureHighTime": 1570312800,
                    "temperatureLow": 55.23,
                    "temperatureLowTime": 1570370400,
                    "apparentTemperatureHigh": 69.42,
                    "apparentTemperatureHighTime": 1570312800,
                    "apparentTemperatureLow": 55.23,
                    "apparentTemperatureLowTime": 1570370400,
                    "dewPoint": 50.98,
                    "humidity": 0.71,
                    "pressure": 1013.89,
                    "windSpeed": 4.9,
                    "windGust": 11.21,
                    "windGustTime": 1570320000,
                    "windBearing": 228,
                    "cloudCover": 0.26,
                    "uvIndex": 6,
                    "uvIndexTime": 1570305600,
                    "visibility": 10,
                    "ozone": 301.8,
                    "temperatureMin": 54.16,
                    "temperatureMinTime": 1570284000,
                    "temperatureMax": 69.42,
                    "temperatureMaxTime": 1570312800,
                    "apparentTemperatureMin": 54.16,
                    "apparentTemperatureMinTime": 1570284000,
                    "apparentTemperatureMax": 69.42,
                    "apparentTemperatureMaxTime": 1570312800
                }
            ]
        },
        "flags": {
            "sources": [
                "nwspa",
                "cmc",
                "gfs",
                "hrrr",
                "icon",
                "isd",
                "madis",
                "nam",
                "sref",
                "darksky",
                "nearest-precip"
            ],
            "nearest-station": 2.24,
            "units": "us"
        },
        "offset": -7
    }
    return null;
  }
}